name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-website:latest .

      - name: Test Docker container
        run: |
          docker run -d --name test-container -p 8081:80 devops-website:latest
          sleep 5
          curl --fail http://localhost:8081
          docker stop test-container
          docker rm test-container
